# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_team.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_choice_team_form(object):
    def setupUi(self, choice_team_form):
        choice_team_form.setObjectName("choice_team_form")
        choice_team_form.resize(972, 467)
        choice_team_form.setMinimumSize(QtCore.QSize(900, 200))
        self.verticalLayout = QtWidgets.QVBoxLayout(choice_team_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(choice_team_form)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tbl = QtWidgets.QTableWidget(choice_team_form)
        self.tbl.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tbl.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl.setObjectName("tbl")
        self.tbl.setColumnCount(0)
        self.tbl.setRowCount(0)
        self.tbl.horizontalHeader().setVisible(False)
        self.tbl.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tbl)

        self.retranslateUi(choice_team_form)
        QtCore.QMetaObject.connectSlotsByName(choice_team_form)

    def retranslateUi(self, choice_team_form):
        _translate = QtCore.QCoreApplication.translate
        choice_team_form.setWindowTitle(_translate("choice_team_form", "Выбор бригады"))
        self.label.setText(_translate("choice_team_form", "Данный сотрудник участвует в нескольких бригадах. Выберите одну."))
